### ISSUE TITLE
how do I make the menu appear on pc?

### ISSUE THREAD

**Issue by Miksol2137** [ShrineFox/Persona-5-Mod-Menu#47]
like seriously i'm reading description of mod for like an hour and i cant find it is there keybind for that?

**Comment by ShrineFox** [comment]
For me it's the N key, or whichever button you have assigned to open the IMs. You also have to be far along enough in the game that the menu is accessible though, I think it's after you start Ryuji's confidant. If the regular IMs menu shows up then something is either wrong with the installation or maybe I goofed somewhere with the mod itself

**Comment by Miksol2137** [comment]
thanks everything is working

**Comment by ShrineFox** [comment]
No problem, glad that's what you needed! I'll consider making it more clear in the instructions
