### ISSUE TITLE
Where's the GitHub.io page?

### ISSUE THREAD

**Issue by Sir-Charles** [ShrineFox/Persona-5-Mod-Menu#9]
Sorry if this is the wrong place to leave this issue, but I was looking through the readme and couldn't get to the shrinefox.github.io page for adding mod.cpk support.. 404 not found. Has this been moved to some other wiki? I'm new to this stuff so I could really use the info.

Thanks!

**Comment by Ean2415** [comment]
amicitia.github.io is the new page now

**Comment by crisdebug** [comment]
It's now amicitia.github.io

**Comment by Sir-Charles** [comment]
Ahh, cool. Thanks for the super quick replies!
